version: '3.7'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ../devnet/database/:/app/db/
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=0.0.0.0